# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Project\python\cash_book\gui\qt-gui\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CashBook(object):
    def setupUi(self, CashBook):
        CashBook.setObjectName("CashBook")
        CashBook.resize(787, 620)
        CashBook.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.main_widget = QtWidgets.QWidget(CashBook)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.content_widget = QtWidgets.QWidget(self.main_widget)
        self.content_widget.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.content_widget.setObjectName("content_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.content_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content_widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.content_page = QtWidgets.QWidget()
        self.content_page.setObjectName("content_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.content_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.content_page)
        self.scrollArea.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 731, 478))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_main = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_main.setMinimumSize(QtCore.QSize(500, 170))
        self.frame_main.setMaximumSize(QtCore.QSize(16777215, 170))
        self.frame_main.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: rgb(150, 150, 150);\n"
"min-width: 10em;\n"
"padding: 6px;")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_main)
        self.gridLayout.setObjectName("gridLayout")
        self.curent_balance_label = QtWidgets.QLabel(self.frame_main)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.curent_balance_label.setFont(font)
        self.curent_balance_label.setStyleSheet("border-style: intset;\n"
"")
        self.curent_balance_label.setAlignment(QtCore.Qt.AlignCenter)
        self.curent_balance_label.setObjectName("curent_balance_label")
        self.gridLayout.addWidget(self.curent_balance_label, 0, 0, 1, 1)
        self.curent_balance = QtWidgets.QLabel(self.frame_main)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.curent_balance.setFont(font)
        self.curent_balance.setStyleSheet("color: green;\n"
"border-style: intset;")
        self.curent_balance.setAlignment(QtCore.Qt.AlignCenter)
        self.curent_balance.setObjectName("curent_balance")
        self.gridLayout.addWidget(self.curent_balance, 0, 1, 1, 1)
        self.total_in_label = QtWidgets.QLabel(self.frame_main)
        font = QtGui.QFont()
        font.setBold(True)
        self.total_in_label.setFont(font)
        self.total_in_label.setObjectName("total_in_label")
        self.gridLayout.addWidget(self.total_in_label, 1, 0, 1, 1)
        self.total_in = QtWidgets.QLabel(self.frame_main)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.total_in.setFont(font)
        self.total_in.setStyleSheet("color: green;")
        self.total_in.setAlignment(QtCore.Qt.AlignCenter)
        self.total_in.setObjectName("total_in")
        self.gridLayout.addWidget(self.total_in, 1, 2, 1, 1)
        self.total_out_label = QtWidgets.QLabel(self.frame_main)
        font = QtGui.QFont()
        font.setBold(True)
        self.total_out_label.setFont(font)
        self.total_out_label.setObjectName("total_out_label")
        self.gridLayout.addWidget(self.total_out_label, 2, 0, 1, 1)
        self.total_out = QtWidgets.QLabel(self.frame_main)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.total_out.setFont(font)
        self.total_out.setStyleSheet("color: red;")
        self.total_out.setAlignment(QtCore.Qt.AlignCenter)
        self.total_out.setObjectName("total_out")
        self.gridLayout.addWidget(self.total_out, 2, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_main)
        self.separator = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.separator.sizePolicy().hasHeightForWidth())
        self.separator.setSizePolicy(sizePolicy)
        self.separator.setMinimumSize(QtCore.QSize(500, 10))
        self.separator.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator.setObjectName("separator")
        self.verticalLayout_5.addWidget(self.separator)
        self.frame_second_1 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_second_1.setMinimumSize(QtCore.QSize(500, 170))
        self.frame_second_1.setMaximumSize(QtCore.QSize(16777215, 170))
        self.frame_second_1.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color:  rgb(150, 150, 150);\n"
"min-width: 10em;\n"
"padding: 6px;")
        self.frame_second_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_second_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_second_1.setObjectName("frame_second_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_second_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.description_label_1 = QtWidgets.QLabel(self.frame_second_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.description_label_1.setFont(font)
        self.description_label_1.setStyleSheet("background-color: rgb(202, 202, 202);\n"
"border-style: intset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color:  rgb(150, 150, 150);\n"
"min-width: 10em;\n"
"padding: 6px;")
        self.description_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.description_label_1.setObjectName("description_label_1")
        self.gridLayout_2.addWidget(self.description_label_1, 0, 0, 3, 1)
        self.event_label_1 = QtWidgets.QLabel(self.frame_second_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.event_label_1.setFont(font)
        self.event_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.event_label_1.setObjectName("event_label_1")
        self.gridLayout_2.addWidget(self.event_label_1, 0, 2, 1, 1)
        self.balance_label_1 = QtWidgets.QLabel(self.frame_second_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.balance_label_1.setFont(font)
        self.balance_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.balance_label_1.setObjectName("balance_label_1")
        self.gridLayout_2.addWidget(self.balance_label_1, 1, 1, 1, 1)
        self.total_balance_1 = QtWidgets.QLabel(self.frame_second_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.total_balance_1.setFont(font)
        self.total_balance_1.setAlignment(QtCore.Qt.AlignCenter)
        self.total_balance_1.setObjectName("total_balance_1")
        self.gridLayout_2.addWidget(self.total_balance_1, 1, 2, 1, 1)
        self.time_label_1 = QtWidgets.QLabel(self.frame_second_1)
        self.time_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label_1.setObjectName("time_label_1")
        self.gridLayout_2.addWidget(self.time_label_1, 2, 1, 1, 2)
        self.verticalLayout_5.addWidget(self.frame_second_1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.frame_btn = QtWidgets.QFrame(self.content_page)
        self.frame_btn.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_btn.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn.setObjectName("frame_btn")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_btn)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cash_in_btn = QtWidgets.QPushButton(self.frame_btn)
        self.cash_in_btn.setMinimumSize(QtCore.QSize(178, 40))
        self.cash_in_btn.setMaximumSize(QtCore.QSize(170, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.cash_in_btn.setFont(font)
        self.cash_in_btn.setStyleSheet("QPushButton {\n"
"    background-color: green;\n"
"    border-style: outset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 86, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    background-color: green;\n"
"    border-style: inset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 86, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px; \n"
"}")
        self.cash_in_btn.setObjectName("cash_in_btn")
        self.horizontalLayout.addWidget(self.cash_in_btn)
        self.cash_out_btn = QtWidgets.QPushButton(self.frame_btn)
        self.cash_out_btn.setMinimumSize(QtCore.QSize(178, 40))
        self.cash_out_btn.setMaximumSize(QtCore.QSize(170, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.cash_out_btn.setFont(font)
        self.cash_out_btn.setStyleSheet("QPushButton {\n"
"background-color: red;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 10px;\n"
"border-color:rgb(158, 0, 0);\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    background-color: red;\n"
"    border-style: inset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(158, 0, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px; \n"
"}")
        self.cash_out_btn.setObjectName("cash_out_btn")
        self.horizontalLayout.addWidget(self.cash_out_btn)
        self.verticalLayout_3.addWidget(self.frame_btn)
        self.stackedWidget.addWidget(self.content_page)
        self.cash_in_out_page = QtWidgets.QWidget()
        self.cash_in_out_page.setObjectName("cash_in_out_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cash_in_out_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.cash_in_out_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.amount_text = QtWidgets.QTextEdit(self.frame)
        self.amount_text.setMinimumSize(QtCore.QSize(500, 32))
        self.amount_text.setMaximumSize(QtCore.QSize(500, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.amount_text.setFont(font)
        self.amount_text.setStyleSheet("")
        self.amount_text.setLineWidth(1)
        self.amount_text.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.amount_text.setObjectName("amount_text")
        self.verticalLayout_7.addWidget(self.amount_text, 0, QtCore.Qt.AlignHCenter)
        self.remark_text = QtWidgets.QTextEdit(self.frame)
        self.remark_text.setMinimumSize(QtCore.QSize(500, 32))
        self.remark_text.setMaximumSize(QtCore.QSize(500, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.remark_text.setFont(font)
        self.remark_text.setObjectName("remark_text")
        self.verticalLayout_7.addWidget(self.remark_text, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.frame)
        self.save_cancel_frame = QtWidgets.QFrame(self.cash_in_out_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_cancel_frame.sizePolicy().hasHeightForWidth())
        self.save_cancel_frame.setSizePolicy(sizePolicy)
        self.save_cancel_frame.setMinimumSize(QtCore.QSize(0, 80))
        self.save_cancel_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.save_cancel_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.save_cancel_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.save_cancel_frame.setObjectName("save_cancel_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.save_cancel_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.save_btn = QtWidgets.QPushButton(self.save_cancel_frame)
        self.save_btn.setMinimumSize(QtCore.QSize(178, 40))
        self.save_btn.setMaximumSize(QtCore.QSize(170, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.save_btn.setFont(font)
        self.save_btn.setStyleSheet("QPushButton {\n"
"    background-color: green;\n"
"    border-style: outset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 86, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    background-color: green;\n"
"    border-style: inset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 86, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px; \n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.save_cancel_frame)
        self.cancel_btn.setMinimumSize(QtCore.QSize(178, 40))
        self.cancel_btn.setMaximumSize(QtCore.QSize(170, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setStyleSheet("QPushButton {\n"
"background-color: red;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 10px;\n"
"border-color:rgb(158, 0, 0);\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    background-color: red;\n"
"    border-style: inset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(158, 0, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px; \n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.verticalLayout_4.addWidget(self.save_cancel_frame, 0, QtCore.Qt.AlignBottom)
        self.stackedWidget.addWidget(self.cash_in_out_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.content_widget)
        CashBook.setCentralWidget(self.main_widget)

        self.retranslateUi(CashBook)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CashBook)

    def retranslateUi(self, CashBook):
        _translate = QtCore.QCoreApplication.translate
        CashBook.setWindowTitle(_translate("CashBook", "MainWindow"))
        self.curent_balance_label.setText(_translate("CashBook", "Balance"))
        self.curent_balance.setText(_translate("CashBook", "0"))
        self.total_in_label.setText(_translate("CashBook", "Total In (+)"))
        self.total_in.setText(_translate("CashBook", "0"))
        self.total_out_label.setText(_translate("CashBook", "Total Out (-)"))
        self.total_out.setText(_translate("CashBook", "0"))
        self.description_label_1.setText(_translate("CashBook", "Description"))
        self.event_label_1.setText(_translate("CashBook", "0"))
        self.balance_label_1.setText(_translate("CashBook", "Balance"))
        self.total_balance_1.setText(_translate("CashBook", "0"))
        self.time_label_1.setText(_translate("CashBook", "Time"))
        self.cash_in_btn.setText(_translate("CashBook", "+  Cash In"))
        self.cash_out_btn.setText(_translate("CashBook", "-  Cash Out"))
        self.amount_text.setPlaceholderText(_translate("CashBook", "Amount*"))
        self.remark_text.setPlaceholderText(_translate("CashBook", "Remark"))
        self.save_btn.setText(_translate("CashBook", "Save"))
        self.cancel_btn.setText(_translate("CashBook", "Cancel"))
